'''urls de la api de iol'''
token = 'https://api.invertironline.com/token'
estadocuenta = 'https://api.invertironline.com/api/v2/estadocuenta'
portafolio = 'https://api.invertironline.com/api/v2/portafolio'
operaciones = 'https://api.invertironline.com/api/v2/operaciones'
operar = 'https://api.invertironline.com/api/v2/operar/Token'
vender = 'https://api.invertironline.com/api/v2/Vender'
comprar = 'https://api.invertironline.com/api/v2/Comprar'
perfil = 'https://api.invertironline.com/api/v2/datos-perfil'
notificaciones = 'https://api.invertironline.com/api/v2/Notificacion'
general = 'https://api.invertironline.com/api/v2/Cotizaciones/acciones/Panel General/argentina'
merval = 'https://api.invertironline.com/api/v2/Cotizaciones/acciones/merval/argentina'
adr = 'https://api.invertironline.com/api/v2/Cotizaciones/adrs/argentina/estados_Unidos'
bonos = 'https://api.invertironline.com/api/v2/Cotizaciones/bonos/Soberanos en dólares/argentina'
cedears = 'https://api.invertironline.com/api/v2/Cotizaciones/Acciones/CEDEARs/Argentina'
sp500 = 'https://api.invertironline.com/api/v2/Cotizaciones/Acciones/SP500/Estados_Unidos'
nasdaq = 'https://api.invertironline.com/api/v2/Cotizaciones/Acciones/Nasdaq 100/Estados_Unidos'
paneles = 'https://api.invertironline.com/api/v2/argentina/Titulos/Cotizacion/Paneles/Acciones'
